Models/Pedidos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Livraria.Models
{
    public class Pedidos
        
    {
        
        [Display(Name = "Pedido Nº")]
        public int Id { get; set; }

        [Required(ErrorMessage = "O pedido deve possuir no mínimo 1 item")]
        [Display(Name = "Quantidade")]
        public int quantidade { get; set; }

        [Required(ErrorMessage = "O pedido deve ter um endereço de entrega")]
        [Display(Name = "Endereço de entrega")]
        public string endereco { get; set; }

        [Required(ErrorMessage = "O pedido deve ter um título selecionado")]
        [Display(Name = "Livro")]
        public int? livroId { get; set; }
        public Livros livro { get; set; }

    }
}

Controllers/LivrosController.cs
using Livraria.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using Livraria.Services;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Livraria.Controllers
{
    public class LivrosController : Controller
    {
        ILivrosService _service, _serviceSql, _serviceStatic, _serviceTudo;
        
       

        public LivrosController(LivrosSqlService serviceSql, LivrariaStaticService serviceStatic, LivrosFullService serviceTudo) 
        {

            this._serviceSql = serviceSql;
            this._serviceStatic = serviceStatic;
            this._serviceTudo = serviceTudo;
            _service = serviceSql;

        }

        public void SelectService(string service="sql") 
        {
            switch (service)
            {
                case "static":
                    this._service = this._serviceStatic;
                    break;
                case "both":
                    this._service = this._serviceTudo;
                    break;
                default:
                    this._service = this._serviceSql;
                    break;
            }
        }


        public  IActionResult Index(IdentityUser user, string busca, bool ordenar = false, string service = "sql")
        {
            SelectService(service);
            ViewBag.ordenar = ordenar;
            ViewBag.total = _service.getAll().Count();
            ViewBag.service = service;
            ViewBag.nome = user.NormalizedUserName;

            return base.View(this._service.getAll(busca, ordenar));
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {   
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [Authorize]
        public IActionResult Create(Livros livro)
        {
            if (!ModelState.IsValid) return View(livro);
            return _service.create(livro) ?
                RedirectToAction(nameof(Index)) : View(livro);
        }

        public IActionResult Read(int? id)
        {
            Livros livros = _service.get(id);
            return livros != null ?
                View(livros) :
                NotFound();
        }

        [Authorize]
        public IActionResult Update(int? id)
        {
            Livros livros = _service.get(id);
            return livros != null ?
                View(livros) :
                NotFound();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Livros livros)
        {
            if (!ModelState.IsValid) return View(livros);
            if (_service.update(livros))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(livros);
            }
        }

        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (_service.delete(id)) 
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

      


       



    }
}

Controllers/PedidosController.cs
using Livraria.Models;
using Livraria.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Livraria.Controllers
{
    public class PedidosController : Controller
    {
        IPedidosService service;
        ILivrosService livrosService;

        public PedidosController(IPedidosService service, ILivrosService livrosService)
        {
            this.service = service;
            this.livrosService = livrosService;
        }

        public IActionResult Index()
        {

            ViewBag.totalPedidos = service.getAll().Count();
            return View(service.getAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            var livros = livrosService.getAll();
            ViewBag.listaDeLivros = new SelectList(livros, "Id", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pedidos pedidos)
        {
            var livros = livrosService.getAll();
            ViewBag.listaDeLivros = new SelectList(livros, "Id", "Nome");
            if (!ModelState.IsValid) return View(pedidos);

            if (service.create(pedidos))
                return RedirectToAction(nameof(Index));
            else
            {

                return View(pedidos);
            }
        }


        public IActionResult Read(int? id)
        {
            Pedidos pedidos = service.get(id);
            return pedidos != null ?
                View(pedidos) :
                NotFound();
        }

        public IActionResult Update(int? id)
        {
            var livros = livrosService.getAll();
            ViewBag.listaDeLivros = new SelectList(livros, "Id", "Nome");
            Pedidos pedidos = service.get(id);
            return pedidos != null ?
                View(pedidos) :
                NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Pedidos pedidos)
        {
            var livros = livrosService.getAll();
            ViewBag.listaDeLivros = new SelectList(livros, "Id", "Nome");
            
            if (!ModelState.IsValid) return View(livros);

            if (service.update(pedidos))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(pedidos);
            }
        }

        public IActionResult Delete(int? id)
        {
            if (service.delete(id))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Views/Pedidos/Create.cshtml
@model Pedidos

<div class="row">
    <form class="col-md-4" asp-action="Create">
        <div class="form-group">
            <label asp-for="livroId" class="control-label"></label>
            <select asp-for="livroId" class="form-control" asp-items="ViewBag.listaDeLivros">
                <option value="">--Selecione o livro do pedido--</option>
            </select>
            <span class="text-danger" asp-validation-for="livroId"></span>
        </div>
        <div class="form-group">
            <label asp-for="endereco" class="control-label"></label>
            <input asp-for="endereco" class="form-control" />
            <span class="text-danger" asp-validation-for="endereco"></span>
        </div>
        <div class="form-group">
            <label  asp-for="quantidade" class="control-label"></label>
            <input type="number" min="1" oninput="this.value = Math.abs(this.value)" asp-for="quantidade" class="form-control" />
            <span class="text-danger" asp-validation-for="quantidade"></span>
        </div>
        
        
        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Fazer pedido!" />
            <a class="btn btn-info" asp-controller="Livros" asp-action="Index">Voltar!</a>
        </div>
    </form>
    
</div>

Views/Pedidos/Index.cshtml
@model List<Pedidos>


<h2>Seus pedidos!</h2>
<a class="btn btn-link" asp-action="Create">Fazer um novo pedido!</a>

<table class="table table-striped table-light">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(Model => Model.First().Id)</th>
            <th>@Html.DisplayNameFor(Model => Model.First().quantidade)</th>
            <th>@Html.DisplayNameFor(Model => Model.First().livro.Nome)</th>
            <th>Ações</th>

</thead>
    <tbody>
        @foreach (Pedidos pedido in Model)
        {
        <tr>
            <td> @Html.DisplayFor(Model => pedido.Id) </td>
            <td> @Html.DisplayFor(Model => pedido.quantidade) </td>
            <td> @Html.DisplayFor(Model => pedido.livro.Nome) </td>
            <td>
                <a class="btn btn-outline-secondary" asp-action="Read" asp-route-id="@pedido.Id">Visualizar</a> |
                <a class="btn btn-outline-secondary" asp-action="Update" asp-route-id="@pedido.Id">Editar</a> |
                <a class="btn btn-outline-secondary" asp-action="Delete" asp-route-id="@pedido.Id">Deletar</a>
            </td>
        </tr>
        }
    </tbody>
</table>
<h6>Você possui @ViewBag.totalPedidos pedido(s) aberto(s).</h6>

Views/Pedidos/Read.cshtml
@model Pedidos
    

@if (Model == null){
<div class="container p-3 mb-2 bg-warning text-white">
    <h5>O pedido não existe nos registros!</h5>
</div>
}
else {

<h1>Pedido @Model.Id</h1>


<dl class="row table table-striped table-dark">
    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Id)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Id)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.livro.Nome)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.livro.Nome)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.quantidade)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.quantidade)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.endereco)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.endereco)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.livro.Sinopse)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.livro.Sinopse)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.livro.Autor)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.livro.Autor)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.livro.Lancamento)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.livro.Lancamento)</dd>
</dl>

}

Views/Pedidos/Update.cshtml
@model Pedidos


<h4>
    Alterar pedido.
</h4>

<div class="row">
    <form class="col-md-4" asp-action="Update">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="quantidade" class="control-label"></label>
            <input type="number" min="1" oninput="this.value = Math.abs(this.value)" asp-for="quantidade" class="form-control" />
            <span class="text-danger" asp-validation-for="quantidade"></span>
        </div>
        <div class="form-group">
            <label asp-for="endereco" class="control-label"></label>
            <input asp-for="endereco" class="form-control" />
            <span class="text-danger" asp-validation-for="endereco"></span>
        </div>
        <div class="form-group">
            <label asp-for="livroId" class="control-label"></label>
            <select asp-for="livroId" class="form-control" asp-items="ViewBag.listaDeLivros">
                <option value="">--Selecione--</option>
            </select>
            <span class="text-danger" asp-validation-for="livroId"></span>
        </div>
        
        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Modificar!" />
            <a class="btn btn-info" asp-controller="Livros" asp-action="Index">Voltar à página principal!</a>
        </div>
    </form>
</div>